- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: install packages on RHEL
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - Mysql
        - git
        - zip
