- name: identify filters
  hosts: localhost
  connection: local
  # vars:
  #   person: laude
  tasks:
    - name: filters
      ansible.builtin.debug:
        msg: "kyaa re {{ person | default ('RANDI')}}"


    - name: convert string to fruits
      vars:
        fruits: "roma,aroma,varoma"
      ansible.builtin.debug:
        msg: "list of fruits: {{fruits | split (',') }}"
      
    - name: convert list into map
      vars:
        course:
          name: coda
          duration: 120days
          trainer: modi
      ansible.builtin.debug:
          msg: "dictionary format to map  is: {{course | dict2items}}"
          
    - name: convert map to list
  hosts: localhost
  connection: local
  vars:
    course:
      - { key: 'name', value: 'coda' }
      - { key: 'duration', value: '120days' }
      - { key: 'trainer', value: 'modi' }
  tasks:
    - name: course info structure
      ansible.builtin.debug:
        msg: "course info structure : {{ course | items2dict }}"


    - name: convert to lower
      vars:
      name: hello re gandu kaisa hai
  ansible.builtin.debug:
      msg: "lower case is {{name | lower}}"

