- name: identify filters
  hosts: localhost
  connection: local
  # vars:
  #   person: laude
  tasks:
    - name: filters
      ansible.builtin.debug:
        msg: "kyaa re {{ person | default ('RANDI')}}"


    - name: convert string to fruits
      vars:
        fruits: "roma,aroma,varoma"
      ansible.builtin.debug:
        msg: "list of fruits: {{fruits | split (',') }}"
      
    - name: convert list into map
      vars:
        course:
          name: coda
          duration: 120days
          trainer: modi
      ansible.builtin.debug:
          msg: "dictionary format to map  is: {{course | dict2items}}"
          
    - name: convert map to list
      course: 
      - {key: 'course' , value: 'coda'}
      - {key: 'duration' , value: '120days'}
      - {key: 'trainer' , value: 'modi'}
      ansible.builtin.debug:
          msg:"{{map to list is : course | items2dict}}"

