- name: identify filters
  hosts: localhost
  connection: local
  # vars:
  #   person: laude
  tasks:
    - name: filters
      ansible.builtin.debug:
        msg: "kyaa re {{ person | default ('RANDI')}}"


    - name: convert string to fruits
      vars:
        fruits: "roma,aroma,varoma"
      ansible.builtin.debug:
        msg: "list of fruits: {{fruits | split (',') }}"
      
    - name: convert map to list
      vars:
        course:
          name: coda
          duration: 120days
          trainer: modi
        ansible.builtin.debug:
          msg: "dictionary format to map  is {{course | dict2items}}"
          

