- name: Install packages
  hosts: webs
  become: yes
  tasks:
    - name: Install multiple packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'java', state: 'present' }
        - { name: 'html', state: 'present' }
        - { name: 'gcc', state: 'present' }
        - { name: 'mysql', state: 'present' }
        - { name: 'docker', state: 'present' }
        - { name: 'pyyaml', state: 'present' }
