- name: convert to lower case
  hosts: local
  connection: local
  tasks:
    vars:
      name: "MANGAL SINGH LOVE MANGAL SINGH"
  tasks:
    ansible.builtin.debug:
    - name: convert to lower case
  msg: "lower case format is  {{ name | upper}}"