- name: uppper to lower case
  hosts: localhost
  connection: local
  vars:
    name: "MANGAL SINGH LOVE SKY"
  tasks:
    - name: convert to lower case
      ansible.builtin.debug:
        msg: "lower case is {{name | lower}}"
