- name: uppper to lower case
  hosts: local
  connection: web
  vars:
    name: "MANGAL SINGH LOVE SKY"
  tasks:
    - name: convert to lower case
      ansible.builtin.debug:
        msg: "lower case is {{name | lower}}"
