- name: shell vs command line
  hosts: local host
  connection: local
  task:
    - name: execute ls commands
      ansible.builtin.command: ls -ltr > /tmpt/output.txt
      # ansible.builtin.shell: ls -lts > /tmp/output.txt
