---
- name: Print course variable from v5-taskvariables.yaml
  hosts: localhost
  connection: local host
  tasks:
    - name: 
      ansible.builtin.debug:
        msg: "Hello {{ name }}, welcome to the {{ course }} course!"
