- name: Print course variable from vars_file
  hosts: localhost
  connection: local


  tasks:
    - name: Display welcome message
      ansible.builtin.debug:
        msg: "Hello {{ name }}, welcome to the {{ course }} course!"