---
- name: Print course variable from 4-variables.yaml
  hosts: localhost
  connection: local host
  tasks:
    - name: Combine All Variables
      ansible.builtin.debug:
        msg: "Hello {{ name }}, welcome to the {{ course }} course!"
