---
- name: Demonstrate conditions in Ansible
  hosts: localhost
  connection: local

  vars:
    course: "Ansible"
    duration: 30
    trainer: "Rahul"
    rating: 4.7

  tasks:
    - name: Display message if course is Ansible
      ansible.builtin.debug:
        msg: "You are learning Ansible!"
      when: course == "Ansible"

    - name: Display message if duration is greater than 20
      ansible.builtin.debug:
        msg: "This is a long-duration course."
      when: duration > 20

    - name: Display message if trainer is Rahul
      ansible.builtin.debug:
        msg: "Trainer is {{ trainer }}"
      when: trainer == "Rahul"

    - name: Display message if rating is less than 4.5
      ansible.builtin.debug:
        msg: "Course rating is below average."
      when: rating < 4.5

    - name: Display message if rating is greater than or equal to 4.5
      ansible.builtin.debug:
        msg: "Course rating is excellent!"
      when: rating >= 4.5
