; [local]
; localhost ansible_connection=local

; [local]
; localhost ansible_connection=local

; [local:vars]
; COURSE=PYTHON
; DURATION=30 days
; TRAINER=John Doe

[webservers]
13.60.98.133 COURSE="ANSIBLE" DURATION="45 days" TRAINER="Jane Smith" ec2-user="ec2-user
ec2-password=2345