; [local]
; localhost ansible_connection=local

; [local]
; localhost ansible_connection=local

; [local:vars]
; COURSE=PYTHON
; DURATION=30 days
; TRAINER=John 

[web]
13.62.126.93 COURSE= "ANSIBLE" DURATION="45 days" TRAINER="Mangal Singh"
ansible_user=ec2-user ansible_password=2345